--- Install-plan construction.
---
--- A plan is inert data describing every file to fetch and where it lands on
--- the device. Building one performs no IO, so the same code answers "what
--- would happen" (`--dry-run`) and "do it".
local path = require("moonman.domain.path")

local plan = {}

--- Source of the generated launcher stub placed at /<name>.lua for packages
--- installed into their own directory. Running the entry point through
--- shell.run keeps CC's require() rooted at the package directory, which is
--- what makes `require("share.ns.mod")` resolve to the vendored copy.
---@param entryPath string absolute path of the package entry point
---@return string
function plan.launcherSource(entryPath)
  return table.concat({
    "-- Generated by moonman. Do not edit.",
    "-- Re-create with: moonman update",
    "local args = { ... }",
    ("return shell.run(%q, table.unpack(args))"):format(entryPath),
    "",
  }, "\n")
end

--- Build the plan for installing a package.
---
--- A package with a single file and no dependencies installs flat as
--- /<name>.lua. Anything else gets its own directory with dependencies
--- vendored under <dir>/share/... and a launcher stub at /<name>.lua.
---@param mf table parsed manifest
---@param pkg table package entry
---@param opts table|nil { as = string }
---@return table|nil plan, string|nil err
function plan.forPackage(mf, pkg, opts)
  opts = opts or {}
  local name = opts.as or path.basename(pkg.name)
  if name == "" then
    return nil, "cannot derive an install name for " .. pkg.name
  end

  local dependencies, err = mf:resolveDependencies(pkg)
  if dependencies == nil then
    return nil, err
  end

  local result = {
    kind = "package",
    name = pkg.name,
    installName = name,
    files = {},
  }

  local flat = #pkg.files == 1 and #dependencies == 0
  if flat then
    result.entry = path.join("/", name .. ".lua")
    result.files[1] = { source = pkg.files[1].source, target = result.entry, role = "entry" }
    return result
  end

  result.root = path.join("/", name)
  result.entry = path.join(result.root, pkg.entry)
  result.launcher = path.join("/", name .. ".lua")

  for _, file in ipairs(pkg.files) do
    result.files[#result.files + 1] = {
      source = file.source,
      target = path.join(result.root, file.target),
      role = "file",
    }
  end
  for _, module in ipairs(dependencies) do
    result.files[#result.files + 1] = {
      source = module.source,
      target = path.join(result.root, path.moduleToPath(module.name)),
      role = "dependency",
      module = module.name,
    }
  end

  local entryFound = false
  for _, file in ipairs(result.files) do
    if file.target == result.entry then
      entryFound = true
      break
    end
  end
  if not entryFound then
    return nil, ("package %s declares entry %q which is not among its files"):format(pkg.name, pkg.entry)
  end

  return result
end

--- Build the plan for installing or refreshing moonman itself.
---@param mf table parsed manifest
---@return table|nil plan, string|nil err
function plan.forMoonman(mf)
  if #mf.moonman.files == 0 then
    return nil, "manifest lists no moonman files"
  end
  local result = {
    kind = "moonman",
    name = "moonman",
    installName = "moonman",
    version = mf.moonman.version,
    files = {},
  }
  for _, file in ipairs(mf.moonman.files) do
    result.files[#result.files + 1] = {
      source = file.source,
      target = path.join("/", file.target),
      role = "file",
    }
  end
  return result
end

--- The device-relative path for a manifest source: src/ is stripped so the
--- installed tree mirrors the repository's src/ rather than nesting under it.
local function deviceRelative(sourcePath)
  return (sourcePath:gsub("^src/", ""))
end

--- Build the plan for a raw path-prefix sync, preserving directory structure.
---
--- The prefix is matched against both the device-relative path and the full
--- repo path, so "share/test" and "src/share/test" both select the same files.
---@param mf table parsed manifest
---@param prefix string path prefix, with or without a leading "src/"
---@param opts table|nil { into = string }
---@return table|nil plan, string|nil err
function plan.forSync(mf, prefix, opts)
  opts = opts or {}
  local dest = path.join("/", opts.into or "")
  local normalisedPrefix = deviceRelative(path.normalise(prefix))

  local result = { kind = "sync", name = normalisedPrefix, installName = normalisedPrefix, files = {} }
  for _, sourcePath in ipairs(mf:sourcePaths()) do
    local relative = deviceRelative(sourcePath)
    if path.hasPrefix(relative, normalisedPrefix) or path.hasPrefix(sourcePath, normalisedPrefix) then
      result.files[#result.files + 1] = {
        source = sourcePath,
        target = path.join(dest, relative),
        role = "file",
      }
    end
  end
  if #result.files == 0 then
    return nil, "no manifest files match \"" .. normalisedPrefix .. "\""
  end
  return result
end

--- Every device path a plan writes, including the launcher stub.
---@param p table
---@return string[]
function plan.targets(p)
  local targets = {}
  for _, file in ipairs(p.files) do
    targets[#targets + 1] = file.target
  end
  if p.launcher then
    targets[#targets + 1] = p.launcher
  end
  return targets
end

return plan
