#!/usr/bin/env bash
# On-device verification in CraftOS-PC.
#
# Lays out a package exactly as moonman's install plan describes -- vendored
# dependencies plus a launcher stub -- and boots a real CC computer to confirm
# that require() resolves. This is the one thing the off-device test suite
# cannot prove, because it depends on CC's own module search path.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"
DIR="$ROOT/.craftos-verify"
COMPUTER="$DIR/computer/0"

rm -rf "$DIR"
mkdir -p "$COMPUTER"

# A package as moonman installs it: entry + sibling + vendored share/ + launcher.
mkdir -p "$COMPUTER/multi_test/share/test"
cp src/player/caboose/multi_test/main.lua  "$COMPUTER/multi_test/main.lua"
cp src/player/caboose/multi_test/test2.lua "$COMPUTER/multi_test/test2.lua"
cp src/share/test/sharetest.lua            "$COMPUTER/multi_test/share/test/sharetest.lua"
cat > "$COMPUTER/multi_test.lua" <<'LAUNCHER'
-- Generated by moonman. Do not edit.
-- Re-create with: moonman update
local args = { ... }
return shell.run("/multi_test/main.lua", table.unpack(args))
LAUNCHER

# moonman as bootstrap installs it: entry at /moonman.lua, tree at /moonman/.
cp moonman/main.lua "$COMPUTER/moonman.lua"
while IFS= read -r file; do
  rel="${file#moonman/}"
  mkdir -p "$COMPUTER/moonman/$(dirname "$rel")"
  cp "$file" "$COMPUTER/moonman/$rel"
done < <(find moonman -name '*.lua' ! -name main.lua)

cat > "$COMPUTER/startup.lua" <<'STARTUP'
local out = fs.open("/results.txt", "w")
local real = { print = _G.print, write = _G.write, printError = _G.printError }

-- shell.run gives child programs an environment indexing into _G, so the
-- globals have to be replaced rather than shadowed locally.
local function capture(label, fn)
  out.writeLine("--- " .. label .. " ---")
  local pending = {}
  local function flush()
    if #pending > 0 then out.writeLine(table.concat(pending)); pending = {} end
  end
  _G.print = function(...)
    local parts = {}
    for i = 1, select("#", ...) do parts[i] = tostring((select(i, ...))) end
    pending[#pending + 1] = table.concat(parts, "\t"); flush()
  end
  _G.write = function(s) pending[#pending + 1] = tostring(s) end
  _G.printError = function(s) flush(); out.writeLine("ERR " .. tostring(s)) end
  local ok, err = pcall(fn)
  flush()
  _G.print, _G.write, _G.printError = real.print, real.write, real.printError
  if not ok then out.writeLine("LUA ERROR: " .. tostring(err)) end
end

capture("package with vendored dependency", function() shell.run("multi_test") end)
capture("moonman help", function() shell.run("moonman", "help") end)
capture("moonman config", function() shell.run("moonman", "config") end)
capture("unknown command", function() shell.run("moonman", "bogus") end)
capture("bad flag", function() shell.run("moonman", "install", "--nope") end)
capture("platform/fs adapter", function()
  local fsPort = require("moonman.platform.fs")
  fsPort.write("/deep/a/b/c.lua", "-- hi")
  print("nested write:", fsPort.exists("/deep/a/b/c.lua"))
  print("read back:", fsPort.read("/deep/a/b/c.lua"))
  fsPort.delete("/deep/a/b/c.lua")
  fsPort.pruneEmptyParents("/deep/a/b/c.lua", "/")
  print("pruned empty parents:", not fsPort.exists("/deep"))
end)
out.close()
os.shutdown()
STARTUP

craftos --headless --directory "$DIR" >/dev/null 2>&1
cat "$COMPUTER/results.txt"

# The vendored and sibling requires are the whole point of the layout.
if ! grep -q "dep test" "$COMPUTER/results.txt" || ! grep -q "hello from test2" "$COMPUTER/results.txt"; then
  echo
  echo "FAILED: require() did not resolve on-device" >&2
  exit 1
fi
if grep -q "LUA ERROR" "$COMPUTER/results.txt"; then
  echo
  echo "FAILED: a command raised a Lua error" >&2
  exit 1
fi
echo
echo "on-device verification passed"
